### ISSUE TITLE
Parent Issue: Translate from Java to Rust

### ISSUE THREAD

**Issue by sibanga** [sibanga/aes#2]
- [x]  Initialize Rust project

- [x]  Add data structures

- [x]  Refactor 

- [x]  Add unit tests
